
"use client"

import Search from './component/searchBar/searchBar'
import Dropdown from './component/dropdown/dropdown'
import CountriesList from './component/countriesList/countriesList'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>title: "REST API for Countries"</title>
        <meta 
          name="description"
          content="Generated by create next app, ReactJS, RESTful api, countries information, tailwind for style, axios for api, Redux for state management, Redux-Thunk Middleware for Asynchronous operations(API)"
        />
      </Head>
      <main className="flex min-h-screen flex-col bg-VeryDarkBlueDarkModeBackground dark:bg-VeryLightGrayLightModeBackground">
        <div className='px-10 py-5 flex flex-col gap-y-8'>
          <div className='flex justify-between flex-col gap-y-8 sm:flex-row'>
            <Search />
            <Dropdown />
          </div>
          <CountriesList />
        </div>
      </main>
    </>
  );
} 
